services:
  - type: web
    name: yaw-backend-api
    env: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: yaw-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: BLOCKCHAIN_NETWORK
        value: african-mainnet
    healthCheckPath: /health
    domains:
      - api.yawnetwork.org
    
  - type: redis
    name: yaw-redis
    plan: starter
    
  - type: postgres
    name: yaw-postgres
    plan: starter
    databaseName: yawnetwork
    user: yaw_admin
